config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'proponentes#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :proponentes do
    resource :contato
    resource :endereco

    collection do
      post 'calcular_inss'
      get 'relatorio' => 'proponentes#relatorio_funcionarios'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contato.rb
class Contato < ApplicationRecord
  belongs_to :proponente
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :proponente
end

app/models/proponente.rb
class Proponente < ApplicationRecord
  has_one :contato, dependent: :destroy
  has_one :endereco, dependent: :destroy

  accepts_nested_attributes_for :contato, allow_destroy: true
  accepts_nested_attributes_for :endereco, allow_destroy: true

  validates :nome, :cpf, :data_nascimento, :salario, presence: true
  validates :cpf, uniqueness: true

  before_save :calcular_e_salvar_inss

  private

  def calcular_e_salvar_inss
    self.desconto_inss = self.class.calcular_desconto_inss(salario)
  end

  # Método de classe para calcular o INSS
  def self.calcular_desconto_inss(salario)
    faixas = [
      { limite: 1045.00, aliquota: 0.075 },
      { limite: 2089.60, aliquota: 0.09 },
      { limite: 3134.40, aliquota: 0.12 },
      { limite: 6101.06, aliquota: 0.14 }
    ]

    desconto_total = 0
    salario_restante = salario

    faixas.each do |faixa|
      if salario_restante > faixa[:limite]
        desconto = (faixa[:limite] - (faixas.index(faixa) > 0 ? faixas[faixas.index(faixa) - 1][:limite] : 0)) * faixa[:aliquota]
        desconto_total += desconto
        salario_restante -= faixa[:limite]
      else
        desconto = salario_restante * faixa[:aliquota]
        desconto_total += desconto
        break
      end
    end

    desconto_total
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_proponente
  before_action :set_contato, only: %i[show edit update destroy]

  def index
    @contatos = @proponente.contatos
  end

  def show; end

  def new
    @contato = @proponente.contatos.build
  end

  def edit; end

  def create
    @contato = @proponente.contatos.build(contato_params)
    if @contato.save
      redirect_to [@proponente, @contato], notice: 'Contato foi criado com sucesso.'
    else
      render :new
    end
  end

  def update
    if @contato.update(contato_params)
      redirect_to [@proponente, @contato], notice: 'Contato foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @contato.destroy
    redirect_to proponente_contatos_url(@proponente), notice: 'Contato foi excluído com sucesso.'
  end

  private

  def set_proponente
    @proponente = Proponente.find(params[:proponente_id])
  end

  def set_contato
    @contato = @proponente.contatos.find(params[:id])
  end

  def contato_params
    params.require(:contato).permit(:telefone, :email)
  end
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_proponente
  before_action :set_endereco, only: %i[show edit update destroy]

  def index
    @enderecos = @proponente.enderecos
  end

  def show; end

  def new
    @endereco = @proponente.enderecos.build
  end

  def edit; end

  def create
    @endereco = @proponente.enderecos.build(endereco_params)
    if @endereco.save
      redirect_to [@proponente, @endereco], notice: 'Endereço foi criado com sucesso.'
    else
      render :new
    end
  end

  def update
    if @endereco.update(endereco_params)
      redirect_to [@proponente, @endereco], notice: 'Endereço foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @endereco.destroy
    redirect_to proponente_enderecos_url(@proponente), notice: 'Endereço foi excluído com sucesso.'
  end

  private

  def set_proponente
    @proponente = Proponente.find(params[:proponente_id])
  end

  def set_endereco
    @endereco = @proponente.enderecos.find(params[:id])
  end

  def endereco_params
    params.require(:endereco).permit(:logradouro, :numero, :bairro, :cidade, :estado, :cep)
  end
end

app/controllers/proponentes_controller.rb
class ProponentesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_proponente, only: %i[show edit update destroy]

  # GET /proponentes or /proponentes.json
  def index
    @proponentes = Proponente.page(params[:page]).per(5)
  end

  # GET /proponentes/1 or /proponentes/1.json
  def show; end

  # GET /proponentes/new
  def new
    @proponente = Proponente.new
    @proponente.build_endereco
    @proponente.build_contato
  end

  # GET /proponentes/1/edit
  def edit; end

  # POST /proponentes or /proponentes.json
  def create
    @proponente = Proponente.new(proponente_params)

    respond_to do |format|
      if @proponente.save
        format.html { redirect_to proponente_url(@proponente), notice: 'Proponente foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @proponente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proponente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proponentes/1 or /proponentes/1.json
  def update
    respond_to do |format|
      if @proponente.update(proponente_params)
        format.html { redirect_to proponente_url(@proponente), notice: 'Proponente alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @proponente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proponente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proponentes/1 or /proponentes/1.json
  def destroy
    @proponente.destroy!

    respond_to do |format|
      format.html { redirect_to proponentes_url, notice: 'Proponente deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  def relatorio_funcionarios
    @funcionarios_faixa_1 = Proponente.where(salario: ..1045.00).count
    @funcionarios_faixa_2 = Proponente.where('salario > ? AND salario <= ?', 1045.00, 2089.60).count
    @funcionarios_faixa_3 = Proponente.where('salario > ? AND salario <= ?', 2089.60, 3134.40).count
    @funcionarios_faixa_4 = Proponente.where('salario > ? AND salario <= ?', 3134.40, 6101.06).count
    @funcionarios_faixa_5 = Proponente.where('salario > ?', 6101.06).count

    @data_for_chart = {
      'Até R$ 1.045,00': @funcionarios_faixa_1,
      'De R$ 1.045,01 a R$ 2.089,60': @funcionarios_faixa_2,
      'De R$ 2.089,60 a R$ 3134.40': @funcionarios_faixa_3,
      'De R$ 3134.40 a R$ 6101.06': @funcionarios_faixa_4,
      'Acima de 6101.06': @funcionarios_faixa_5
    }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_proponente
    @proponente = Proponente.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def proponente_params
    params.require(:proponente).permit(:nome, :cpf, :data_nascimento, :salario, :desconto_inss,
                                       endereco_attributes: %i[id logradouro numero bairro cidade estado cep _destroy],
                                       contato_attributes: %i[id telefone email _destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DescontoInss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proponentes/_form.html.erb
<%= form_with(model: proponente, local: true, html: {class: 'container mt-3'}) do |form| %>
  <% if proponente.errors.any? %>
    <div class="alert alert-danger">
      <% count = proponente.errors.count %>
      <h2><%= t("errors.header", count: count) %></h2>
      <ul>
        <% proponente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Proponente -->
  <div class="container bg-light p-3 mb-3">
    <h4>Proponente</h4>
    <div class="row mb-3">
      <div class="col-md-6">
        <%= form.label :nome, 'Nome', class: 'form-label' %>
        <%= form.text_field :nome, class: 'form-control', id: 'nome' %>
      </div>
      <div class="col-md-6">
        <%= form.label :data_nascimento, 'Data de Nascimento', class: 'form-label' %>
        <%= form.text_field :data_nascimento, class: 'form-control', id: 'data_nascimento' %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-4">
        <%= form.label :cpf, 'CPF', class: 'form-label' %>
        <%= form.text_field :cpf, class: 'form-control', id: 'cpf' %>
      </div>
      <div class="col-md-4">
        <%= form.label :salario, 'Salário', class: 'form-label' %>
        <%= form.text_field :salario, class: 'form-control', id: 'salario' %>
      </div>
      <div class="col-md-4">
        <%= form.label :desconto_inss, 'Desconto INSS', class: 'form-label' %>
        <%= form.text_field :desconto_inss, class: 'form-control', id: 'desconto_inss_field', disabled: true %>
      </div>

    </div>
  </div>

  <!-- Contato -->
  <div class="container bg-light p-3 mb-3">
    <h4>Contato</h4>
    <%= form.fields_for :contato do |contato_fields| %>
      <div class="row mb-3">
        <div class="col-md-6">
          <%= contato_fields.label :telefone, 'Telefone', class: 'form-label' %>
          <%= contato_fields.telephone_field :telefone, class: 'form-control', id: 'telefone' %>
        </div>
        <div class="col-md-6">
          <%= contato_fields.label :email, 'Email', class: 'form-label' %>
          <%= contato_fields.text_field :email, class: 'form-control', id: 'email' %>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Endereço -->
  <div class="container bg-light p-3 mb-3">
    <h4>Endereço</h4>
    <%= form.fields_for :endereco do |endereco_fields| %>
      <div class="row mb-3">
        <div class="col-md-12">
          <%= endereco_fields.label :logradouro, 'Logradouro', class: 'form-label' %>
          <%= endereco_fields.text_field :logradouro, class: 'form-control', id: 'logradouro' %>
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-4">
          <%= endereco_fields.label :numero, 'Número', class: 'form-label' %>
          <%= endereco_fields.text_field :numero, class: 'form-control', id: 'numero' %>
        </div>
        <div class="col-md-4">
          <%= endereco_fields.label :bairro, 'Bairro', class: 'form-label' %>
          <%= endereco_fields.text_field :bairro, class: 'form-control', id: 'bairro' %>
        </div>
        <div class="col-md-4">
          <%= endereco_fields.label :cep, 'CEP', class: 'form-label' %>
          <%= endereco_fields.text_field :cep, class: 'form-control', id: 'cep' %>
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-6">
          <%= endereco_fields.label :cidade, 'Cidade', class: 'form-label' %>
          <%= endereco_fields.text_field :cidade, class: 'form-control', id: 'cidade' %>
        </div>
        <div class="col-md-6">
          <%= endereco_fields.label :estado, 'Estado', class: 'form-label' %>
          <%= endereco_fields.text_field :estado, class: 'form-control', id: 'estado' %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-12 text-right">
      <%= form.submit "Salvar", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<script>
    document.addEventListener("turbo:load", function() {
        $('#salario').on('change', function() {
            console.log("passando aqui")
            debugger
            var salario = $(this).val();  // Pega o valor do campo salário
            $.ajax({
                url: '<%= calcular_inss_proponentes_path %>', // Endpoint configurado no seu routes.rb
                type: 'POST', // Verifique se o método no seu controller aceita POST
                dataType: 'json', // Espera-se que a resposta seja JSON
                data: {
                    salario: salario,
                    authenticity_token: $('meta[name="csrf-token"]').attr('content') // CSRF token
                },
                success: function(response) {
                    $('#desconto_inss_field').val(response.desconto_inss.toFixed(2)); // Atualiza o campo desconto_inss
                },
                error: function(xhr) {
                    console.error('Erro ao calcular o desconto do INSS:', xhr);
                }
            });
        });
    });
</script>

app/views/proponentes/_proponente.html.erb
<tr id="<%= dom_id(proponente) %>">
  <td><%= proponente.nome %></td>
  <td><%= proponente.cpf %></td>
  <td><%= proponente.data_nascimento %></td>
  <td><%= proponente.endereco.logradouro %></td>
  <td><%= proponente.endereco.numero %></td>
  <td><%= proponente.endereco.bairro %></td>
  <td><%= proponente.endereco.cidade %></td>
  <td><%= proponente.endereco.estado %></td>
  <td><%= proponente.endereco.cep %></td>
  <td><%= proponente.contato.telefone %></td>
  <td><%= number_to_currency(proponente.salario) %></td>
  <td><%= number_to_currency(proponente.desconto_inss) %></td>
  <td>
    <%= link_to 'Show', proponente, class: 'btn btn-info' %>
    <%= link_to 'Edit', edit_proponente_path(proponente), class: 'btn btn-primary' %>
    <%= link_to 'Delete', proponente, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </td>

</tr>

app/views/proponentes/edit.html.erb
<h1>Editar proponente</h1>

<%= render "form", proponente: @proponente %>

<br>

<div>
  <%= link_to "Visualizar", @proponente, class: 'btn btn-info' %>
  <%= link_to "Voltar", proponentes_path, class: 'btn btn-secondary' %>
</div>

app/views/proponentes/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1>Proponentes</h1>

  <%= link_to "New proponente", new_proponente_path, class: "btn btn-primary", role: "button" %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Nome</th>
        <th>CPF</th>
        <th>Data de Nascimento</th>
        <th>Endereço</th>
        <th>Número</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th>CEP</th>
        <th>Telefone</th>
        <th>Salário</th>
        <th> Desconto INSS</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @proponentes.each do |proponente| %>
        <%= render 'proponente', proponente: proponente %>
      <% end %>
      </tbody>
    </table>
    <div class="pagination-container">
      <%= paginate @proponentes %>
    </div>
  </div>

  <div>
    <%= link_to 'Relatório de Funcionários', relatorio_proponentes_path, class: 'btn btn-primary' %>
  </div>
</div>
<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger', data: { turbo_method: :delete } %>

app/views/proponentes/new.html.erb
<h1>New proponente</h1>

<%= render "form", proponente: @proponente %>

<br>

<div>
  <%= link_to "Back to proponentes", proponentes_path %>
</div>

app/views/proponentes/relatorio_funcionarios.html.erb
<!-- app/views/proponentes/relatorio_funcionarios.html.erb -->
<h3 class="text-center mb-4">Relatório de Funcionários por Faixa Salarial</h3>

<div class="container">
  <div class="row">
    <!-- Container para o relatório textual -->
    <div class="col-md-6">
      <div class="card text-center mb-3">
        <div class="card-header">
          Faixa Salarial: Até R$ 1.045,00
        </div>
        <div class="card-body">
          <h5 class="card-title">Quantidade de Funcionários</h5>
          <p class="card-text"><%= @funcionarios_faixa_1 %></p>
        </div>
      </div>
      <div class="card text-center mb-3">
        <div class="card-header">
          Faixa Salarial: De R$ 1.045,01 a R$ 2.089,60
        </div>
        <div class="card-body">
          <h5 class="card-title">Quantidade de Funcionários</h5>
          <p class="card-text"><%= @funcionarios_faixa_2 %></p>
        </div>
      </div>
      <div class="card text-center mb-3">
        <div class="card-header">
          Faixa Salarial: De R$ 2.089,61 a R$ 3.134,40
        </div>
        <div class="card-body">
          <h5 class="card-title">Quantidade de Funcionários</h5>
          <p class="card-text"><%= @funcionarios_faixa_3 %></p>
        </div>
      </div>
      <div class="card text-center mb-3">
        <div class="card-header">
          Faixa Salarial: De R$ 3.134,41 a R$ 6.101,06
        </div>
        <div class="card-body">
          <h5 class="card-title">Quantidade de Funcionários</h5>
          <p class="card-text"><%= @funcionarios_faixa_4 %></p>
        </div>
      </div>
      <div class="card text-center mb-3">
        <div class="card-header">
          Faixa Salarial: Acima de R$ 6.101,06
        </div>
        <div class="card-body">
          <h5 class="card-title">Quantidade de Funcionários</h5>
          <p class="card-text"><%= @funcionarios_faixa_5 %></p>
        </div>
      </div>
    </div>

    <!-- Container para o gráfico -->
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          Gráfico da Distribuição de Funcionários por Faixa Salarial
        </div>
        <div class="card-body">
          <%= pie_chart @data_for_chart, library: {title: {text: 'Funcionários por Faixa', x: -20}}, donut: true, legend: "bottom" %>
        </div>
      </div>
    </div>
  </div>

  <!-- Botão de retorno ao índice -->
  <div class="row">
    <div class="col-md-12 text-center mt-4 mb-4">
      <%= link_to 'Voltar para o Índice', proponentes_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/proponentes/show.html.erb
<!-- app/views/proponentes/show.html.erb -->
<div class="container mt-3">
  <h3>Detalhes do Proponente</h3>
  <div class="container bg-light p-3 mb-3">
    <div class="row mb-3">
      <div class="col-md-6">
        <strong>Nome:</strong>
        <%= @proponente.nome %>
      </div>
      <div class="col-md-6">
        <strong>Data de Nascimento:</strong>
        <%= @proponente.data_nascimento %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-4">
        <strong>CPF:</strong>
        <%= @proponente.cpf %>
      </div>
      <div class="col-md-4">
        <strong>Salário:</strong>
        <%= number_to_currency(@proponente.salario) %>
      </div>
      <div class="col-md-4">
        <strong>Desconto INSS:</strong>
        <%= number_to_currency(@proponente.desconto_inss) %>
      </div>
    </div>
  </div>

  <h3>Contato</h3>
  <div class="container bg-light p-3 mb-3">
    <div class="row mb-3">
      <div class="col-md-6">
        <strong>Telefone:</strong>
        <%= @proponente.contato.telefone %>
      </div>
      <div class="col-md-6">
        <strong>Email:</strong>
        <%= @proponente.contato.email %>
      </div>
    </div>
  </div>

  <h3>Endereço</h3>
  <div class="container bg-light p-3 mb-3">
    <div class="row mb-3">
      <div class="col-md-12">
        <strong>Logradouro:</strong>
        <%= @proponente.endereco.logradouro %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-4">
        <strong>Número:</strong>
        <%= @proponente.endereco.numero %>
      </div>
      <div class="col-md-4">
        <strong>Bairro:</strong>
        <%= @proponente.endereco.bairro %>
      </div>
      <div class="col-md-4">
        <strong>CEP:</strong>
        <%= @proponente.endereco.cep %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-6">
        <strong>Cidade:</strong>
        <%= @proponente.endereco.cidade %>
      </div>
      <div class="col-md-6">
        <strong>Estado:</strong>
        <%= @proponente.endereco.estado %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Voltar', proponentes_path, class: 'btn btn-secondary' %>
      <%= link_to 'Editar', edit_proponente_path(@proponente), class: 'btn btn-primary' %>
    </div>
  </div>
</div>